version: '3.7'

volumes:
#  db_data: {}
  postgres_data: {}
  pgadmin: {}
  prometheus_data: {}
  grafana_data: {}

services:
  
  postgres:
    image: postgres:12
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres!pw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    environment:
       - DB_USER=dbuser
       - DB_PASSWORD=postgres!pw
       - DB_HOST=db
       - DB_NAME=postgres
       - POOL_MODE=transaction
       - ADMIN_USERS=postgres,dbuser
    ports:
      - 5432:5432
    depends_on:
      - postgres     
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
#      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
      
    ports:
      - 9090:9090  

 #   command:
 #     - '--config.file=/etc/prometheus/prometheus.yml'
 #     - '--storage.tsdb.path=/prometheus'
 #     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
 #     - '--web.console.templates=/usr/share/prometheus/consoles'
 #     - '--web.route-prefix=/'
 #     - '--web.external-url=/prometheus/'
    restart: always    


  grafana:
#   image: registry.gear.ge.com/503240122/grafana:8.5.5
    image: grafana/grafana-enterprise:9.3.2-ubuntu
    container_name: grafana
    user: "root"

    links:
      - prometheus
#      - loki
#      - promtail
    depends_on:
      - prometheus
#      - loki
#      - promtail
    volumes:
      - grafana_data:/var/lib/grafana
#      - ./grafana/provisioning/img/fav32.png:/usr/share/grafana/public/img/fav32.png:rw

    environment:
      - GF_SERVER_DOMAIN=grafana
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_USERS_DEFAULT_THEME=dark
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    
    ports:
      - 3000:3000
    
  pgadmin_client:
    container_name: pgadmin4-container
    image: dpage/pgadmin4
    restart: unless-stopped
    expose:
      - 5050
    environment:
      PGADMIN_DEFAULT_EMAIL: lajos.misurda@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin:/var/lib/pgadmin      
    ports:
      - 5050:80     