version: '3.7'

volumes:
#  db_data: {}
  postgres_data: {}
  pgadmin: {}
  prometheus_data: {}
  grafana_data: {}

services:
  postgresdb:
    image: postgres:12
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    restart: always
    environment:
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: postgres!pw
      POSTGRES_DB: northwind_db

  pgbouncer:
    image: pgbouncer/pgbouncer
    restart: always
    depends_on:
      - postgresdb
    ports:
      - 6432:6432
    environment:
      # AUTH_TYPE: md5
      # AUTH_FILE: /etc/pgbouncer/userlist.txt
      PGBOUNCER_AUTH_USER: northwind_user
      PGBOUNCER_AUTH_PASSWORD: postgres!pw
      PGBOUNCER_DEFAULT_POOL_SIZE: 20
      PGBOUNCER_MAX_CLIENT_CONN: 100
      PGBOUNCER_POOL_MODE: session
      PGBOUNCER_POOL_SIZE: 20
      PGBOUNCER_SERVER_IDLE_TIMEOUT: 60
      PGBOUNCER_SERVER_IDLE_TRANSACTION_TIMEOUT: 300
      PGBOUNCER_SERVER_ROUND_ROBIN: 1
      PGBOUNCER_SERVERS: postgresdb:5432/northwind_db
      
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      
    ports:
      - 9090:9090  

 #   command:
 #     - '--config.file=/etc/prometheus/prometheus.yml'
 #     - '--storage.tsdb.path=/prometheus'
 #     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
 #     - '--web.console.templates=/usr/share/prometheus/consoles'
 #     - '--web.route-prefix=/'
 #     - '--web.external-url=/prometheus/'
    restart: always    

  grafana:
    image: grafana/grafana-enterprise:9.3.2-ubuntu
    container_name: grafana
    user: "root"

    links:
      - prometheus	  
    depends_on:

      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

    environment:
      - GF_SERVER_DOMAIN=grafana
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_USERS_DEFAULT_THEME=dark
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    
    ports:
      - 3000:3000
    
  pgadmin_client:
    container_name: pgadmin4-container
    image: dpage/pgadmin4
    restart: unless-stopped
    expose:
      - 5050
    environment:
      PGADMIN_DEFAULT_EMAIL: lajos.misurda@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin:/var/lib/pgadmin      
    ports:
      - 5050:80     